// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_70CGBslYHkfqk6_RomyrpXYuaeTYW0c',
    appId: '1:756811489851:web:965b0ba311c3104561b21e',
    messagingSenderId: '756811489851',
    projectId: 'flutter-apirest',
    authDomain: 'flutter-apirest.firebaseapp.com',
    storageBucket: 'flutter-apirest.firebasestorage.app',
    measurementId: 'G-FF3MKFDPQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-OZEATmg0uI7tGndDznFsXW5eIDifAY',
    appId: '1:756811489851:android:3d3526ade1826de061b21e',
    messagingSenderId: '756811489851',
    projectId: 'flutter-apirest',
    storageBucket: 'flutter-apirest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2NwiBNjN1gqcyyhgCnIF7PquodG9d5c',
    appId: '1:756811489851:ios:e1a80b696d6dc87561b21e',
    messagingSenderId: '756811489851',
    projectId: 'flutter-apirest',
    storageBucket: 'flutter-apirest.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2NwiBNjN1gqcyyhgCnIF7PquodG9d5c',
    appId: '1:756811489851:ios:e1a80b696d6dc87561b21e',
    messagingSenderId: '756811489851',
    projectId: 'flutter-apirest',
    storageBucket: 'flutter-apirest.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_70CGBslYHkfqk6_RomyrpXYuaeTYW0c',
    appId: '1:756811489851:web:aa816a438a8c0f1761b21e',
    messagingSenderId: '756811489851',
    projectId: 'flutter-apirest',
    authDomain: 'flutter-apirest.firebaseapp.com',
    storageBucket: 'flutter-apirest.firebasestorage.app',
    measurementId: 'G-EJC7PCZ14P',
  );

}